config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resources :events, only: [:new, :create, :show]
  resources :invitations, only: [:create]
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :invitations
  has_many :invitations
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :invitations
  has_many :attending_events, :through => :invitations,
            :class_name => 'Event',
            :foreign_key => 'event_id',
            :source => :event
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    session[:current_user]    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    if current_user
      @event = User.find(current_user).events.new
    else
      flash[:notice] = "Login to create an event."
      redirect_to login_path
    end
  end

  def create
    user = User.find(current_user)
    @event = user.events.new(event_params)
    @event.save
    redirect_to user
  end

  def show
    @event = Event.find(params[:id])
  end

  private
    def event_params
      params.require(:event).permit(:location, :date)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    user = User.find_by(name: params[:name])
    if user
      @event = Event.find(params[:event_id])
      @event.invitations.create(user_id: user.id)

      redirect_to user
    else
      flash[:notice] = "Not a valid user"
      redirect_to event_path(params[:event_id])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      session[:current_user] = @user.id
      redirect_to @user
    else
      flash.now[:notice] = "User not found"
      render :new
    end
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if user.save
      redirect_to user_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).allow(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attending_events.where("date >= ?", Time.now)
    @past_events     = @user.attending_events.where("date < ?", Time.now)
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/new.html.erb
<h1>Create event</h1>

<h4>Event owner: <%= User.find(@event.user_id).name %></h4>
<div>
  <%= form_for @event do |f| %>
    <%= f.label :location %>
    <%= f.text_field :location %><br/>

    <%= f.label :date %><br/>
    <%= f.datetime_select :date %><br/>

    <%= f.submit 'Create event' %>
  <% end %>
</div>

app/views/events/show.html.erb
<h1>Event</h1>

<h4>location: </h4><%= @event.location %>
<p>
Time: <%= @event.date %>
</p>

<h3>Add invitation:</h3>
<div>
  <%= form_tag(invitations_path, method: 'post' ) do %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>

    <%= hidden_field_tag 'event_id', @event.id %>


    <%= submit_tag "add invitation" %>
  <% end %>
</div>

<div>
  <h3>Attendees</h3>
  <% @event.invitations.each do |invite| %>
    <%= link_to invite.user.name, invite.user %><br/>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <div id="flash"><%=  flash[:notice] %></div>
<% end %>

<%= link_to("create event", new_event_path) %>
<%= link_to "users", users_path %>

<%= yield %>

</body>
</html>

app/views/shared/_event.html.erb
Location: <%= event.location %><br/>
Time: <%= event.date %><br/>

app/views/shared/_invitation.html.erb
<%= form_tag(invitations_path, method: 'post' ) do %>
  <%= label_tag :name %>
  <%= text_field_tag :invitation, :name %>

  <%= submit_tag "add invitation" %>
<% end %>

app/views/users/index.html.erb
<h1>Users:</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user %><br/>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name if @user %>'s profile:</h1>

<div class="events">
  <h3>Events:</h3>
  <% @user.events.each do |event| %>
    <div>
      Location: <%=  event.location %><br/>
      Time: <%=  event.date %><br/>
      <%= link_to("manage", event_path(event.id)) %>
     </div>
  <% end %>
</div>

<h3>Attending:</h3>
<h4>Upcoming events:</h4>
<div class="attending">
  <div class="upcoming-events">
    <% @upcoming_events.each do |event| %>
      <%= render 'shared/event', :event => event %>
    <% end %>
  </div>
  <h4>Past events:</h4>
  <div class="past-events">
    <% @past_events.each do |event| %>
      <%= render 'shared/event', :event => event %>
    <% end %>
  </div>
</div>